---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "ctse-user-client-service"
  namespace: "default"
  labels:
    app: "ctse-user-client"
spec:
  ports:
  - protocol: "TCP"
    port: 3000
  selector:
    app: "ctse-user-client"
  type: "LoadBalancer"
  loadBalancerIP: ""
